# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('rgb(255, 138, 128)', 'red'), ('rgb(128, 216, 255)', 'blue'), ('rgb(255, 255, 141)', 'yellow'), ('rgb(255, 209, 128)', 'orange'), ('rgb(204, 255, 144)', 'green'), ('rgb(207, 216, 220)', 'grey'), ('rgb(167, 255, 235)', 'teal')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
